RoSky\Bundle\NoodleBundle\Entity\GamesList:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        pname:
            type: string
            length: 50
        pcount:
            type: integer
        gname:
            type: string
            length: 100
        gstatus:
            type: string
            length: 50
    lifecycleCallbacks: {  }
