RoSky\Bundle\NoodleBundle\Entity\GamesList:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
        players:
            type: integer
    lifecycleCallbacks: {  }
