parameters:
#    ro_sky_noodle.example.class: RoSky\Bundle\NoodleBundle\Example

services:
#    ro_sky_noodle.example:
#        class: %ro_sky_noodle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
